CREATE TABLE users (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
hashed_password VARCHAR(250) NOT NULL,
created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE documents (
id SERIAL PRIMARY KEY,
filename VARCHAR(150) NOT NULL,
file_path VARCHAR(250) NOT NULL UNIQUE,
uploaded_by INTEGER NOT NULL REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE document_chunks(
    id SERIAL PRIMARY KEY,
    document_id INTEGER REFERENCES documents(id),
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
)
